// AUTO-GENERATED by scripts/sync-cafe24-detail-images.mjs

export type GeneratedCafe24DetailImageSet = {
  sourceLabel: string;
  sourceUrl: string;
  urls: string[];
  checkedAt: string;
};

export const CAFE24_DETAIL_SYNC_CHECKED_AT = "";
export const generatedCafe24DetailImageSetsByModel: Record<string, GeneratedCafe24DetailImageSet> = {};
