// AUTO-GENERATED by scripts/sync-greymall-detail-images.mjs
// Greymall is used only as a source of exact-model long-form DETAIL images.
// Product names, prices, benefit codes, hero images, and distribution data are not overwritten.

export type GeneratedGreymallDetailImageSet = {
  sourceLabel: string;
  sourceUrl: string;
  urls: string[];
  checkedAt: string;
};

export const GREYMALL_DETAIL_SYNC_CHECKED_AT = '';

export const generatedGreymallDetailImageSetsBySlug: Record<string, GeneratedGreymallDetailImageSet> = {};
// Temporary compatibility alias while the generated sync migrates from model-keyed to public-slug-keyed data.
export const generatedGreymallDetailImageSetsByModel = generatedGreymallDetailImageSetsBySlug;
