// AUTO-GENERATED by scripts/sync-carestore-detail-images.mjs
// Carestore is used only as an exact-benefit-code fallback source for long-form DETAIL images.
// Product names, prices, benefit codes, hero images, and distribution data are not overwritten.

export type GeneratedCarestoreDetailImageSet = {
  sourceLabel: string;
  sourceUrl: string;
  urls: string[];
  checkedAt: string;
};

export const CARESTORE_DETAIL_SYNC_CHECKED_AT = "";

export const generatedCarestoreDetailImageSetsByModel: Record<string, GeneratedCarestoreDetailImageSet> = {};
