// AUTO-GENERATED by scripts/sync-gagaon-detail-images.mjs
// Gagaon storefronts are used only as exact-benefit-code fallback sources for long-form DETAIL images.

export type GeneratedGagaonDetailImageSet = {
  sourceLabel: string;
  sourceUrl: string;
  urls: string[];
  checkedAt: string;
};

export const GAGAON_DETAIL_SYNC_CHECKED_AT = "";
export const generatedGagaonDetailImageSetsByModel: Record<string, GeneratedGagaonDetailImageSet> = {};
