import type { Product } from './products';

export const verifiedBatch4: Product[] = [
  {
    slug: 'sw-m260-anti-slip-mat',
    name: 'SW-M260',
    model: 'SW-M260',
    manufacturer: '세원케어',
    benefitCode: 'F30031091104',
    category: '미끄럼방지용품',
    benefitPrice: 44000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '욕실과 생활공간의 미끄러짐을 줄이는 PVC 격자형 미끄럼방지매트입니다.',
    material: 'PVC',
    dimensions: '100 × 260 × 1.4cm',
    weightKg: 7.7,
    maxQuantityPerCycle: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/F30031091104',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'bofeel9-bath-chair',
    name: 'BOFEEL9',
    model: 'BOFEEL9',
    manufacturer: '보필',
    benefitCode: 'B03180025013',
    category: '목욕의자',
    benefitPrice: 157000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '접이식 알루미늄 프레임과 EVA 좌면을 사용하는 높이 조절형 목욕의자입니다.',
    material: '알루미늄, EVA, PP 등',
    dimensions: '54 × 50~56 × 72~79cm (좌면높이 36.5~43cm)',
    weightKg: 4.9,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/B03180025013',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'isa-carbon-cane',
    name: 'ISA',
    model: 'ISA',
    manufacturer: '아이온',
    benefitCode: 'M03031033101',
    category: '지팡이',
    benefitPrice: 40000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '카본 소재를 사용한 단족형 높이 조절 지팡이입니다. 네오디뮴 자석 손잡이와 미끄럼 방지 고무발을 적용한 제품입니다.',
    material: '카본, 알루미늄, 합성고무, 네오디뮴자석',
    dimensions: '길이 72~96cm (9단계 조절)',
    weightKg: 0.23,
    purchaseCycleYears: 2,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M03031033101',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'bls-900-anti-slip-mat',
    name: 'BLS-900',
    model: 'BLS-900',
    manufacturer: '(주)보림엘텍',
    benefitCode: 'F30031151106',
    category: '미끄럼방지용품',
    benefitPrice: 34100,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '어두운 환경에서도 위치를 확인하기 쉬운 축광 실리콘 소재의 미끄럼방지매트입니다.',
    material: '축광 실리콘',
    dimensions: '56.1 × 107.2 × 0.28cm',
    weightKg: 2.1,
    maxQuantityPerCycle: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/F30031151106',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'samb-portable-toilet',
    name: 'SAMB',
    model: 'SAMB',
    manufacturer: '보필',
    benefitCode: 'T03030025001',
    category: '이동변기',
    benefitPrice: 122000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '알루미늄 프레임을 사용한 경량 이동변기로, 높이 조절과 접이 보관이 가능한 제품입니다.',
    material: '알루미늄, 폴리프로필렌',
    dimensions: '56 × 49 × 78~85cm',
    weightKg: 4.8,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중·내구연한 교차검증',
        url: 'https://www.carestore.co.kr/welfare/T03030025001',
        checkedAt: '2026-09-12',
      },
    ],
  },
];
