import type { Product } from './products';

export const verifiedBatch2: Product[] = [
  {
    slug: 'nice-walker-4s',
    name: '나이스워커4S',
    model: '나이스워커4S',
    manufacturer: '나이스텍',
    benefitCode: 'M06060004003',
    category: '성인용보행기',
    benefitPrice: 328000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '실내 보행을 돕는 4륜형 성인용보행기입니다. 높이 조절과 좌우 레버 브레이크, 속도조절 구조를 갖춘 제품입니다.',
    material: '스테인리스, 알루미늄, 합성수지',
    dimensions: '61 × 71.5 × 75~90cm',
    weightKg: 9.5,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·규격 교차검증', url: 'https://www.carestore.co.kr/welfare/M06060004003', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'slt-10-silver-walker',
    name: 'SLT-10',
    model: 'SLT-10',
    manufacturer: '(주)미라클메디',
    benefitCode: 'M06090217501',
    category: '성인용보행기',
    benefitPrice: 214000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '좌석과 수납공간을 갖춘 실버카형 성인용보행기입니다. 접이식 구조와 높이 조절 손잡이로 일상 보행을 보조합니다.',
    material: '알루미늄',
    dimensions: '54.5 × 64 × 81.5~94cm',
    weightKg: 6.6,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/M06090217501', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'pn-l4152101d-bath-chair',
    name: 'PN-L4152101D',
    model: 'PN-L4152101D',
    manufacturer: '(주)신동아이에스',
    benefitCode: 'B03180081503',
    category: '목욕의자',
    benefitPrice: 187000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '파나소닉 계열의 접이식 목욕의자로, 알루미늄 프레임과 EVA 시트를 사용하고 높이 조절이 가능한 제품입니다.',
    material: '알루미늄, EVA, PE',
    dimensions: '50.5 × 50~58.5 × 68~78cm',
    weightKg: 5.1,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/B03180081503', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'bofeel10-bath-chair',
    name: 'BOFEEL10',
    model: 'BOFEEL10',
    manufacturer: '보필',
    benefitCode: 'B03180025012',
    category: '목욕의자',
    benefitPrice: 171000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '알루미늄 프레임과 EVA 시트를 사용하는 접이식 목욕의자입니다. 좌면 높이와 팔걸이를 조절해 사용할 수 있습니다.',
    material: '알루미늄, EVA, PP',
    dimensions: '54 × 50~56 × 72~79cm',
    weightKg: 5,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/B03180025012', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'ash-103-safety-handle',
    name: 'ASH-103',
    model: 'ASH-103',
    manufacturer: '(주)에이엠이',
    benefitCode: 'F18030060004',
    category: '안전손잡이',
    benefitPrice: 44400,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=13&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '벽면에 설치해 이동과 자세 변경을 보조하는 원목형 안전손잡이입니다.',
    material: '천연목, 아연합금',
    dimensions: '60 × 5.5cm',
    weightKg: 0.6,
    purchaseCycleYears: 1,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=13&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F18030060004', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'apt-101-portable-toilet',
    name: 'APT-101',
    model: 'APT-101',
    manufacturer: '(주)에이엠이',
    benefitCode: 'T03030060001',
    category: '이동변기',
    benefitPrice: 306000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '거주공간에서 배변을 보조하기 위한 원목형 이동변기입니다. 높이를 단계별로 조절할 수 있습니다.',
    material: '목재, 우레탄, PP',
    dimensions: '47 × 55 × 85/88/91cm',
    weightKg: 16.2,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가 확인', url: 'https://eroumcare.com/shop/search.php', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/T03030060001', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'da-006-anti-slip-mat',
    name: 'DA-006',
    model: 'DA-006',
    manufacturer: '대아',
    benefitCode: 'F30031036108',
    category: '미끄럼방지용품',
    benefitPrice: 74400,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '욕실이나 현관 등 미끄러질 수 있는 공간에 사용하는 격자형 미끄럼방지매트입니다.',
    material: '연질 PVC, 우레탄',
    dimensions: '90 × 200 × 1.4cm',
    weightKg: 11.5,
    purchaseCycleYears: 1,
    maxQuantityPerCycle: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F30031036108', checkedAt: '2026-09-12' },
    ],
  },
];
