import type { Product } from './products';

// 목욕의자 전체 후보 중 이로움 현재 상태를 확인한 결과를 보관합니다.
// ACTIVE만 사이트에 노출되며 비유통/단종 제품은 자동으로 게시 대상에서 제외됩니다.
export const pendingBathChairs: Product[] = [
  {
    slug: 'asc-502-bath-chair',
    name: 'ASC-502',
    model: 'ASC-502',
    manufacturer: '(주)에이엠이',
    benefitCode: 'B03180060004',
    category: '목욕의자',
    benefitPrice: 186000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=2&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '팔걸이와 U자형 좌면을 갖춘 높이조절형 목욕의자 급여제품입니다.',
    material: '알루미늄, EVA, PE',
    dimensions: '46 × 46.5~55.5 × 60.7~70.6cm / 좌면높이 39~49cm',
    weightKg: 4.5,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=2&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/B03180060004', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'iu-bath-chair',
    name: 'IU',
    model: 'IU',
    manufacturer: '케어맥스코리아',
    benefitCode: 'B03180088605',
    category: '목욕의자',
    benefitPrice: 175000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=2&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '접이식 알루미늄 프레임과 높이조절 구조를 갖춘 목욕의자 급여제품입니다.',
    material: '알루미늄, EVA, 폴리프로필렌',
    dimensions: '51 × 46~53 × 64~74cm / 좌면높이 35~45cm',
    weightKg: 5,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 유통·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=2&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·가격·유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/B03180088605', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'kscu01-bath-chair',
    name: 'KSCU01',
    model: 'KSCU01',
    manufacturer: '(주)리스케어',
    benefitCode: 'B03180195501',
    category: '목욕의자',
    benefitPrice: 168000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/B03180195501',
    sourceCheckedAt: '2026-09-12',
    description: '수입 목욕의자 급여제품입니다. 이로움 현재 판매상태 최종 확인 전까지 공개하지 않습니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [{ label: '급여코드·가격·공단 유통중 확인', url: 'https://www.carestore.co.kr/welfare/B03180195501', checkedAt: '2026-09-12' }],
  },
  {
    slug: 'rsc01-bath-chair',
    name: 'RSC01',
    model: 'RSC01',
    manufacturer: '(주)리스케어',
    benefitCode: 'B03180228501',
    category: '목욕의자',
    benefitPrice: 175000,
    status: 'NOT_DISTRIBUTED',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=39&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 비유통·품절로 확인되어 사이트 공개 대상에서 제외한 목욕의자입니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 비유통·품절 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=39&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·공단 데이터 교차확인', url: 'https://www.carestore.co.kr/welfare/B03180228501', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'k-100-bath-chair',
    name: 'K-100',
    model: 'K-100',
    manufacturer: '산케어',
    benefitCode: 'B03181173601',
    category: '목욕의자',
    benefitPrice: 162000,
    status: 'DISCONTINUED',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=40&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 비유통·단종·품절로 확인되어 사이트 공개 대상에서 제외한 목욕의자입니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 비유통·단종·품절 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=40&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·공단 데이터 교차확인', url: 'https://www.carestore.co.kr/welfare/B03181173601', checkedAt: '2026-09-12' },
    ],
  },
];
