import type { Product } from './products';

// 공단 반영 최신 유통 데이터에서는 유통중으로 확인됐지만,
// 이로움 공개 화면에서 정상 유통 상태를 직접 재확인하지 못한 후보입니다.
// PENDING_EROUm_VERIFICATION 상태이므로 사이트에는 노출되지 않습니다.
export const pendingBatch6: Product[] = [
  {
    slug: 'gc-r10-adult-walker',
    name: 'GC-R10',
    model: 'GC-R10',
    manufacturer: '주식회사 고친',
    benefitCode: 'M06060231001',
    category: '성인용보행기',
    benefitPrice: 421000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/M06060231001',
    sourceCheckedAt: '2026-09-12',
    description: '원터치 스토퍼와 접이 구조를 갖춘 알루미늄 롤레이터형 성인용보행기입니다.',
    material: '알루미늄, 폴리에스테르',
    dimensions: '56 × 71 × 82~97cm',
    weightKg: 6.5,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '급여코드·가격·유통중 확인',
        url: 'https://www.carestore.co.kr/welfare/M06060231001',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'activefree-op5-adult-walker',
    name: 'ActiveFree OP5',
    model: 'ActiveFree OP5',
    manufacturer: 'SDF INTERNATIONAL CO.,LTD',
    benefitCode: 'M06061283601',
    category: '성인용보행기',
    benefitPrice: 450000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/M06061283601',
    sourceCheckedAt: '2026-09-12',
    description: '복지용구 급여제품으로 등록된 성인용보행기입니다. 현재 이로움 유통상태 직접 확인을 대기 중입니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '급여코드·가격·유통중 확인',
        url: 'https://www.carestore.co.kr/welfare/M06061283601',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'spirit-x4-adult-walker',
    name: '스피릿x4',
    model: '스피릿x4',
    manufacturer: '메디케어코리아',
    benefitCode: 'M06061088601',
    category: '성인용보행기',
    benefitPrice: 448000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/M06061088601',
    sourceCheckedAt: '2026-09-12',
    description: '복지용구 급여제품으로 등록된 성인용보행기입니다. 현재 이로움 유통상태 직접 확인을 대기 중입니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '급여코드·가격·유통중 확인',
        url: 'https://www.carestore.co.kr/welfare/M06061088601',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'cozywalker-p04-adult-walker',
    name: '코지워커P04',
    model: '코지워커P04',
    manufacturer: '주식회사 코지케어',
    benefitCode: 'M06061056103',
    category: '성인용보행기',
    benefitPrice: 256000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/M06061056103',
    sourceCheckedAt: '2026-09-12',
    description: '국산 성인용보행기 급여제품입니다. 현재 이로움 유통상태 직접 확인을 대기 중입니다.',
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '급여코드·가격·유통중 확인',
        url: 'https://www.carestore.co.kr/welfare/M06061056103',
        checkedAt: '2026-09-12',
      },
    ],
  },
];
