import type { Product } from './products';

export const activeCurrentBatch: Product[] = [
  {
    slug: 'bls-900-anti-slip-mat',
    name: 'BLS-900',
    model: 'BLS-900',
    manufacturer: '(주)보림엘텍',
    benefitCode: 'F30031151106',
    category: '미끄럼방지용품',
    benefitPrice: 34100,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '축광 실리콘 소재의 미끄럼방지매트로 욕실과 생활공간의 미끄럼 위험을 줄이는 데 사용하는 복지용구입니다.',
    material: '축광 실리콘',
    dimensions: '56.1 × 107.2 × 0.28cm',
    weightKg: 2.1,
    maxQuantityPerCycle: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 현재 상품검색 정상 노출·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/F30031151106',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'isa-cane',
    name: 'ISA',
    model: 'ISA',
    manufacturer: '아이온',
    benefitCode: 'M03031033101',
    category: '지팡이',
    benefitPrice: 40000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '카본 소재를 사용한 길이조절형 지팡이로 일상 보행을 보조하는 복지용구입니다.',
    material: '카본, 알루미늄, 합성고무, 네오디뮴자석',
    dimensions: '길이 72~96cm (9단계 조절)',
    weightKg: 0.23,
    purchaseCycleYears: 2,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 현재 상품검색 정상 노출·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M03031033101',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'samb-portable-toilet',
    name: 'SAMB',
    model: 'SAMB',
    manufacturer: '보필',
    benefitCode: 'T03030025001',
    category: '이동변기',
    benefitPrice: 122000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '알루미늄 프레임과 폴리프로필렌 변기 구조를 사용한 높이조절형 이동변기입니다.',
    material: '알루미늄, 폴리프로필렌',
    dimensions: '56 × 49 × 78~85cm',
    weightKg: 4.8,
    purchaseCycleYears: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 현재 상품검색 정상 노출·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=5&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·규격 교차검증',
        url: 'https://www.udcares.co.kr/%EA%B0%84%EC%9D%B4%EB%B3%80%EA%B8%B0%E3%85%A3%EC%9D%B4%EB%8F%99%EB%B3%80%EA%B8%B0',
        checkedAt: '2026-09-12',
      },
    ],
  },
];
