import type { Product } from './products';

export const verifiedBatch6: Product[] = [
  {
    slug: 'lp-021-incontinence-underwear',
    name: 'LP-021 보나수 50cc',
    model: 'LP-021',
    manufacturer: '주식회사 에르핏',
    benefitCode: 'T09061123101',
    category: '요실금팬티',
    benefitPrice: 27600,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '면 소재의 여성용 요실금팬티로 50cc 흡수용량과 M~XXL 사이즈 구성을 갖춘 장기요양 복지용구입니다.',
    material: '면',
    dimensions: 'M(95), L(100), XL(105), XXL(110)',
    weightKg: 0.056,
    maxQuantityPerCycle: 4,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·가격·규격 확인',
        url: 'https://eroumcare.com/shop/search.php',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중·급여한도 교차검증',
        url: 'https://www.carestore.co.kr/welfare/T09061123101',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'abp-105-bedpan-urinal',
    name: 'ABP-105',
    model: 'ABP-105',
    manufacturer: '(주)에이엠이',
    benefitCode: 'T03060060101',
    category: '간이변기',
    benefitPrice: 14300,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=3&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '남성용 간이소변기로 침상이나 생활공간에서 배뇨를 보조하는 장기요양 복지용구입니다.',
    material: '폴리프로필렌, TPR, PVC',
    dimensions: '10.5 × 29 × 11cm / 용량 1L',
    weightKg: 0.172,
    maxQuantityPerCycle: 2,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·가격·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=3&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중·급여한도 교차검증',
        url: 'https://www.carestore.co.kr/welfare/T03060060101',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'ata-4030-positioning-aid',
    name: 'ATA-4030',
    model: 'ATA-4030',
    manufacturer: '(주)에이엠이',
    benefitCode: 'M30030060109',
    category: '자세변환용구',
    benefitPrice: 36000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=12&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '침상에서 자세 변경과 자세 유지를 보조하는 우레탄 소재의 자세변환용구입니다.',
    material: '우레탄',
    dimensions: '40 × 30 × 17cm',
    weightKg: 0.66,
    maxQuantityPerCycle: 5,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·가격·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=12&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중·급여한도 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M30030060109',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'ygm3-indoor-ramp',
    name: 'YGM3',
    model: 'YGM3',
    manufacturer: '유광정밀',
    benefitCode: 'F24000045002',
    category: '경사로(실내용)',
    benefitPrice: 95100,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '실내 문턱과 단차를 해소해 보행기·휠체어 이동을 돕는 알루미늄 경사로입니다.',
    material: '알루미늄, ABS수지',
    dimensions: '75 × 29 × 5cm / 적용 문턱높이 3.5~5.6cm',
    weightKg: 2.58,
    purchaseCycleYears: 2,
    maxQuantityPerCycle: 6,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·가격·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중·규격 교차검증',
        url: 'https://www.carestore.co.kr/welfare/F24000045002',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'miki-jtn-manual-wheelchair',
    name: 'MIKI-JTN',
    model: 'MIKI-JTN',
    manufacturer: '미키코리아메디칼',
    benefitCode: 'M18030111513',
    category: '수동휠체어',
    benefitPrice: 34400,
    benefitMode: 'RENTAL',
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '알루미늄 프레임과 PU 타이어를 사용하는 장기요양 수동휠체어 대여제품입니다. 월 대여 급여가격을 기준으로 본인부담금을 계산합니다.',
    material: '알루미늄, PU타이어',
    dimensions: '62 × 101.5 × 89cm',
    weightKg: 15.8,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 노출·월 급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=14&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '대여 급여코드·월 가격·유통중·내구연한 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M18030111513',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'ds-801a-manual-wheelchair',
    name: 'DS-801A',
    model: 'DS-801A',
    manufacturer: '디에스아이',
    benefitCode: 'M18031074601',
    category: '수동휠체어',
    benefitPrice: 31200,
    benefitMode: 'RENTAL',
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=23&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '알루미늄 프레임과 PU 타이어를 사용하는 수동휠체어 대여제품입니다. 월 대여 급여가격 기준으로 본인부담금을 확인할 수 있습니다.',
    material: '알루미늄, PU타이어',
    dimensions: '64 × 103 × 89cm',
    weightKg: 16,
    purchaseCycleYears: 5,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·월 급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=23&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '대여 급여코드·월 가격·유통중·내구연한 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M18031074601',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'se7030-electric-bed',
    name: 'SE7030',
    model: 'SE7030',
    manufacturer: '성심 ENG',
    benefitCode: 'S03090183002',
    category: '전동침대',
    benefitPrice: 76500,
    benefitMode: 'RENTAL',
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=25&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '등판·높이 등을 전동으로 조절하는 장기요양 전동침대 대여제품입니다. 월 대여 급여가격 기준으로 본인부담금을 계산합니다.',
    material: 'PP, PU, 철제',
    dimensions: '95 × 216 × 31~68cm',
    weightKg: 96,
    purchaseCycleYears: 10,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 설치상품·월 급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=25&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '대여 급여코드·월 가격·유통중·내구연한 교차검증',
        url: 'https://www.carestore.co.kr/welfare/S03090183002',
        checkedAt: '2026-09-12',
      },
    ],
  },
];
