import type { Product } from './products';

// 안전손잡이 전체 후보의 이로움 현재 판매상태를 반영합니다.
// ACTIVE만 공개되며 일시품절·비유통 제품은 자동 제외됩니다.
export const pendingSafetyHandles: Product[] = [
  {
    slug: 'sj-100-safety-handle',
    name: 'SJ-100',
    model: 'SJ-100',
    manufacturer: '삼주유니콘',
    benefitCode: 'F18030050001',
    category: '안전손잡이',
    benefitPrice: 42300,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/F18030050001',
    sourceCheckedAt: '2026-09-12',
    description: '고령자의 이동과 자세변경을 보조하는 거치형 안전손잡이입니다. 이로움 현재 판매상태 최종 확인 전까지 공개하지 않습니다.',
    material: '알루미늄, EP발포고무',
    dimensions: '40.5 × 40.5 × 34cm',
    weightKg: 0.9,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [{ label: '급여코드·급여가·공단 유통중 확인', url: 'https://www.carestore.co.kr/welfare/F18030050001', checkedAt: '2026-09-12' }],
  },
  {
    slug: 'ash-212-safety-handle',
    name: 'ASH-212',
    model: 'ASH-212',
    manufacturer: '(주)에이엠이',
    benefitCode: 'F18030060030',
    category: '안전손잡이',
    benefitPrice: 257400,
    status: 'TEMP_OUT_OF_STOCK',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=38&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 일시품절 예약가능 상태로 확인되어 공개 대상에서 제외한 기둥형 안전손잡이입니다.',
    material: '알루미늄, 가죽(PU)',
    dimensions: '본체 높이 204~335cm / 손잡이직경 4~4.5cm',
    weightKg: 5.7,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 일시품절 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=38&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가 교차확인', url: 'https://www.carestore.co.kr/welfare/F18030060030', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'ash-402-safety-handle',
    name: 'ASH-402',
    model: 'ASH-402',
    manufacturer: '(주)에이엠이',
    benefitCode: 'F18030060031',
    category: '안전손잡이',
    benefitPrice: 176000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/F18030060031',
    sourceCheckedAt: '2026-09-12',
    description: '양변기 주변에서 일어서기와 착석을 보조하는 거치형 안전손잡이입니다. 이로움 현재 판매상태 최종 확인 전까지 공개하지 않습니다.',
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [{ label: '급여코드·급여가·공단 유통중 확인', url: 'https://www.carestore.co.kr/welfare/F18030060031', checkedAt: '2026-09-12' }],
  },
  {
    slug: 'msp-0002-safety-handle',
    name: 'MSP-0002',
    model: 'MSP-0002',
    manufacturer: '주식회사 명성실버케어',
    benefitCode: 'F18030175003',
    category: '안전손잡이',
    benefitPrice: 240000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=13&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '스틸 프레임 기반의 거치형 안전손잡이로 생활공간에서 일어서기와 이동을 보조합니다.',
    material: '스틸파이프, 도장철판, PVC',
    dimensions: '52 × 92 × 81~91cm / 손잡이직경 3.5cm',
    weightKg: 21.7,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 판매·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=1&page=13&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가·공단 유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F18030175003', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'dgp-0006-safety-handle',
    name: 'DGP-0006',
    model: 'DGP-0006',
    manufacturer: '주식회사 대구정공',
    benefitCode: 'F18030059006',
    category: '안전손잡이',
    benefitPrice: 37400,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=18&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '기둥형 손잡이에 결합해 이동 시 지지점을 제공하는 안전손잡이 급여제품입니다.',
    material: 'PVC, PIPE, 나일론',
    dimensions: '길이 23.5cm / 손잡이직경 3.5cm',
    weightKg: 1,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 판매·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=18&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가·공단 유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F18030059006', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'csh-1000-safety-handle',
    name: 'CSH-1000',
    model: 'CSH-1000',
    manufacturer: '세비앙',
    benefitCode: 'F18031026106',
    category: '안전손잡이',
    benefitPrice: 174000,
    status: 'PENDING_EROUM_VERIFICATION',
    sourceUrl: 'https://www.carestore.co.kr/welfare/F18031026106',
    sourceCheckedAt: '2026-09-12',
    description: '변기 주변에서 일어서기와 착석을 보조하는 안전손잡이입니다. 이로움 현재 판매상태 최종 확인 전까지 공개하지 않습니다.',
    material: '알루미늄, 원목',
    dimensions: '약 57.5 × 50.5 × 63.8~71.8cm',
    weightKg: 6.5,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [{ label: '급여코드·급여가·공단 유통중 확인', url: 'https://www.carestore.co.kr/welfare/F18031026106', checkedAt: '2026-09-12' }],
  },
  {
    slug: 'dgp-0002-safety-handle',
    name: 'DGP-0002',
    model: 'DGP-0002',
    manufacturer: '주식회사 대구정공',
    benefitCode: 'F18030059002',
    category: '안전손잡이',
    benefitPrice: 158000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=26&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '스틸 프레임의 거치형 안전손잡이로 생활공간에서 일어서기와 이동을 보조합니다.',
    material: '스틸',
    dimensions: '52 × 92 × 70cm / 손잡이직경 3.5cm',
    weightKg: 17,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 판매·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=26&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가·공단 유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F18030059002', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'ash-503-safety-handle',
    name: 'ASH-503',
    model: 'ASH-503',
    manufacturer: '(주)에이엠이',
    benefitCode: 'F18030060029',
    category: '안전손잡이',
    benefitPrice: 200000,
    status: 'TEMP_OUT_OF_STOCK',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=27&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 일시품절 예약가능 상태로 확인되어 공개 대상에서 제외한 거치형 안전손잡이입니다.',
    material: '스틸, 알루미늄, PVC, PA',
    dimensions: '78 × 48 × 72~85cm',
    weightKg: 15.7,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 일시품절 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=27&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가 교차확인', url: 'https://www.carestore.co.kr/welfare/F18030060029', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'sfb-03-safety-handle',
    name: 'SFB-03',
    model: 'SFB-03',
    manufacturer: '삼인라이프롬(Samin.Lifrom)',
    benefitCode: 'F18030078003',
    category: '안전손잡이',
    benefitPrice: 38800,
    status: 'NOT_DISTRIBUTED',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=44&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 비유통 상품으로 확인되어 사이트 공개 대상에서 제외한 안전손잡이입니다.',
    material: '목재(미송), PCPBT',
    dimensions: '길이 62cm × 높이 8.5cm / 손잡이둘레 35Φ',
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 비유통 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmaker=&itmodel=&page=44&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가 교차확인', url: 'https://www.carestore.co.kr/welfare/F18030078003', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'ash-502-safety-handle',
    name: 'ASH-502',
    model: 'ASH-502',
    manufacturer: '(주)에이엠이',
    benefitCode: 'F18030060028',
    category: '안전손잡이',
    benefitPrice: 240000,
    status: 'TEMP_OUT_OF_STOCK',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=38&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: '이로움에서 일시품절 예약가능 상태로 확인되어 공개 대상에서 제외한 거치형 안전손잡이입니다.',
    material: '스틸, 알루미늄, PVC, PA',
    dimensions: '78 × 48 × 72~85cm',
    weightKg: 17.2,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 일시품절 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=38&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가 교차확인', url: 'https://www.carestore.co.kr/welfare/F18030060028', checkedAt: '2026-09-12' },
    ],
  },
  {
    slug: 'cd-10-safety-handle',
    name: 'CD-10',
    model: 'CD-10',
    manufacturer: '제이케이 다올',
    benefitCode: 'F18031082101',
    category: '안전손잡이',
    benefitPrice: 257000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=11&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '기둥형 구조로 생활공간에서 일어서기와 이동을 보조하는 안전손잡이 급여제품입니다.',
    material: '알루미늄, ABS, 스틸, 실리콘',
    dimensions: '높이조절 파이프 110cm / 손잡이 파이프 직경 3.5~4.0cm',
    weightKg: 4.55,
    maxQuantityPerCycle: 10,
    imageRightsConfirmed: false,
    verificationSources: [
      { label: '이로움 정상 판매·급여가·규격 확인', url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=11&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=', checkedAt: '2026-09-12' },
      { label: '급여코드·급여가·공단 유통중 교차검증', url: 'https://www.carestore.co.kr/welfare/F18031082101', checkedAt: '2026-09-12' },
    ],
  },
];
