import type { Product } from './products';

export const verifiedBatch3: Product[] = [
  {
    slug: 'ss-carbon-cane',
    name: 'SS',
    model: 'SS',
    manufacturer: '(주)아이온',
    benefitCode: 'M03030132002',
    category: '지팡이',
    benefitPrice: 44400,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php',
    sourceCheckedAt: '2026-09-12',
    description: '카본 소재를 사용한 높이 조절형 보행보조 지팡이입니다. 가벼운 무게와 길이 조절 구조로 일상 보행을 보조합니다.',
    material: '카본, 합성고무, 합성수지',
    dimensions: '길이 75~100cm (10단계 조절)',
    weightKg: 0.34,
    purchaseCycleYears: 2,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 현재 정상 유통·급여가 확인',
        url: 'https://eroumcare.com/shop/search.php',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/M03030132002',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'glory-11-pressure-cushion',
    name: 'GLORY-11',
    model: 'GLORY-11',
    manufacturer: '(주)포에버헬스케어',
    benefitCode: 'H12030130009',
    category: '욕창예방방석',
    benefitPrice: 195000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=25&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
    sourceCheckedAt: '2026-09-12',
    description: '장시간 착석 시 압력 분산을 돕는 욕창예방방석입니다. 방석과 전용 커버로 구성된 급여 제품입니다.',
    material: 'Poly, 에어매쉬(Poly) 외',
    dimensions: '방석 40 × 43 × 5cm / 커버 40.5 × 43.5 × 6.5cm',
    weightKg: 1.08,
    purchaseCycleYears: 3,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 유통·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=25&pttag=&q=&qbasic=&qexplan=&qid=&qname=1&qorder=&qsort=&qtag=',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/H12030130009',
        checkedAt: '2026-09-12',
      },
    ],
  },
  {
    slug: 'yh-0302tpu-pressure-mattress',
    name: 'YH-0302TPU',
    model: 'YH-0302TPU',
    manufacturer: '영화의료기',
    benefitCode: 'H12060031101',
    category: '욕창예방매트리스',
    benefitPrice: 281000,
    status: 'ACTIVE',
    sourceUrl: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=31&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
    sourceCheckedAt: '2026-09-12',
    description: 'TPU 소재의 교대부양 방식 욕창예방매트리스입니다. 장시간 침상 생활 시 신체 압력 분산을 돕는 급여 제품입니다.',
    material: 'TPU',
    dimensions: '80 × 185 × 8cm',
    weightKg: 4.5,
    purchaseCycleYears: 3,
    maxQuantityPerCycle: 1,
    imageRightsConfirmed: false,
    verificationSources: [
      {
        label: '이로움 정상 노출·급여가·규격 확인',
        url: 'https://eroumcare.com/shop/search.php?ca_id=&itmodel=&page=31&pttag=&q=&qbasic=1&qexplan=1&qid=1&qname=1&qorder=&qsort=&qtag=1',
        checkedAt: '2026-09-12',
      },
      {
        label: '급여코드·구입가격·유통중 교차검증',
        url: 'https://www.carestore.co.kr/welfare/H12060031101',
        checkedAt: '2026-09-12',
      },
    ],
  },
];
